FROM ubuntu:14.04

RUN apt-get update -yq && apt-get -yq install curl

RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

RUN apt-get update -yq && \
    apt-get install -yq \
        build-essential \
        git-core \
        nodejs \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY package.json /app/package.json
RUN cd /app; npm install
RUN npm install --global babel-cli
RUN npm install --global nodemon

COPY settings.json /app/settings.json
COPY . /app

EXPOSE 3000
CMD [ "babel-node", "/app/src/index.js" ]
