web:
  build: .
  command: nodemon --exec "babel-node /app/src/index.js" -w "/app/src"
  links:
    - db
  volumes:
    - ./src:/app/src
    - ./public:/app/public
    - ./views:/app/views
    - /app/node_modules
    - ./settings.json:/app/settings.json
  ports:
    - "3000:3000"
db:
  image: mongo
